In [3]:
import numpy as np

In [4]:
c = np.array([[1, 2], [3, 4]])

In [5]:
c.shape

(2, 2)

In [7]:
c.ndim

2

In [8]:
c.size

4

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [13]:
e = np.empty([3, 4])

[[ 2.20054750e-314  1.48219694e-323  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  3.95252517e-323  0.00000000e+000  0.00000000e+000]
 [-1.18917335e+194  6.94134787e-310  6.94134882e-310 -1.29074148e-231]]


In [15]:
f = np.eye(5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
np.array([1, 2], dtype = np.float32)

array([1., 2.], dtype=float32)

In [18]:
g = np.arange(10, 20, 2)
g

array([10, 12, 14, 16, 18])

In [25]:
h = np.linspace(0, 99, 5)
h

array([ 0.  , 24.75, 49.5 , 74.25, 99.  ])

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [26]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
result = a * b

In [30]:
"result : %result" % result

'result : array([ 1,  4,  9, 16])esult'

In [31]:
twod = np.array([[1,2], [3,4,5]])
twod.flat

In [34]:
twod.flat[:]

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [35]:
np.transpose(twod)

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [36]:
b = [[1, 0], [0, 1]]
print(b)

[[1, 0], [0, 1]]


In [37]:
np.transpose(b)

array([[1, 0],
       [0, 1]])

In [38]:
a = np.arange(6).reshape(2, 3)

In [39]:
a

array([[0, 1, 2],
       [3, 4, 5]])